// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3GOT6W3Q5fZ_n9LIw-Vb78pS8llFMk1w',
    appId: '1:953045886148:web:1d8bde401d5ed142851591',
    messagingSenderId: '953045886148',
    projectId: 'flash-chat-1cee5',
    authDomain: 'flash-chat-1cee5.firebaseapp.com',
    storageBucket: 'flash-chat-1cee5.appspot.com',
    measurementId: 'G-BMVGTHNC5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbi_ZALCrRIX8sLVsNUsg4xcUaiTonf10',
    appId: '1:953045886148:android:05c07d39a5a7bbf6851591',
    messagingSenderId: '953045886148',
    projectId: 'flash-chat-1cee5',
    storageBucket: 'flash-chat-1cee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw46tOh14IG45Qyxxw2uMc2I-jnxmPWiM',
    appId: '1:953045886148:ios:eda8985fec20f74a851591',
    messagingSenderId: '953045886148',
    projectId: 'flash-chat-1cee5',
    storageBucket: 'flash-chat-1cee5.appspot.com',
    iosClientId: '953045886148-bavqsngfd5s2e4jgnsljqgrulpv7fq4q.apps.googleusercontent.com',
    iosBundleId: 'com.DerrikPollock.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw46tOh14IG45Qyxxw2uMc2I-jnxmPWiM',
    appId: '1:953045886148:ios:557f6ece13e8d668851591',
    messagingSenderId: '953045886148',
    projectId: 'flash-chat-1cee5',
    storageBucket: 'flash-chat-1cee5.appspot.com',
    iosClientId: '953045886148-7l1sj84s1b3ajlj9mo2rg8ih31ipi1lm.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
